# Generated by Django 3.1 on 2020-10-25 13:30

import Users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20201025_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=Users.models.Document.uppath),
        ),
    ]
