# Generated by Django 2.1 on 2020-06-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Area1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='image',
            field=models.URLField(default=None, null=True),
        ),
    ]
